//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyManagement.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PropertyEntities : DbContext
    {
        public PropertyEntities()
            : base("name=PropertyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tbl_CustomerKin> tbl_CustomerKin { get; set; }
        public virtual DbSet<tbl_CustomerRegM> tbl_CustomerRegM { get; set; }
        public virtual DbSet<tbl_Files> tbl_Files { get; set; }
        public virtual DbSet<tbl_InstDetail> tbl_InstDetail { get; set; }
        public virtual DbSet<tbl_InstMaster> tbl_InstMaster { get; set; }
        public virtual DbSet<tbl_InstReceived> tbl_InstReceived { get; set; }
        public virtual DbSet<tbl_List> tbl_List { get; set; }
        public virtual DbSet<tbl_Menu> tbl_Menu { get; set; }
        public virtual DbSet<tbl_Projects> tbl_Projects { get; set; }
        public virtual DbSet<tbl_UserLogin> tbl_UserLogin { get; set; }
        public virtual DbSet<tbl_userMenu> tbl_userMenu { get; set; }
        public virtual DbSet<tbl_UserRole> tbl_UserRole { get; set; }
        public virtual DbSet<tbl_CustomerFileBook> tbl_CustomerFileBook { get; set; }
        public virtual DbSet<View_CustomerFileBooking> View_CustomerFileBooking { get; set; }
        public virtual DbSet<View_Installment_Receive> View_Installment_Receive { get; set; }
    
        public virtual int Pro_CheckLogin(string pARM_USER_NAME, string pARM_PASSWORD, ObjectParameter pARM_USER_ID, ObjectParameter pARM_FULL_USER_NAME, ObjectParameter pARM_USER_ROLE, ObjectParameter pARM_ERROR_MESSAGE)
        {
            var pARM_USER_NAMEParameter = pARM_USER_NAME != null ?
                new ObjectParameter("PARM_USER_NAME", pARM_USER_NAME) :
                new ObjectParameter("PARM_USER_NAME", typeof(string));
    
            var pARM_PASSWORDParameter = pARM_PASSWORD != null ?
                new ObjectParameter("PARM_PASSWORD", pARM_PASSWORD) :
                new ObjectParameter("PARM_PASSWORD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pro_CheckLogin", pARM_USER_NAMEParameter, pARM_PASSWORDParameter, pARM_USER_ID, pARM_FULL_USER_NAME, pARM_USER_ROLE, pARM_ERROR_MESSAGE);
        }
    
        public virtual int Pro_IDU_CustomerKin(string pARM_IDU_STS, Nullable<long> pARAM_CustomerKinId, Nullable<long> pARAM_fkCustomerId, string pARAM_KinName, string pARAM_KinCNIC, string pARAM_KinMobile, string pARAM_KinRelation, string pARAM_ActiveYN, string pARAM_CreatedBy, Nullable<System.DateTime> pARAM_CreatedDate, string pARAM_UpdatedBy, Nullable<System.DateTime> pARAM_UpdatedDate, ObjectParameter pARM_ERROR_MESSAGE)
        {
            var pARM_IDU_STSParameter = pARM_IDU_STS != null ?
                new ObjectParameter("PARM_IDU_STS", pARM_IDU_STS) :
                new ObjectParameter("PARM_IDU_STS", typeof(string));
    
            var pARAM_CustomerKinIdParameter = pARAM_CustomerKinId.HasValue ?
                new ObjectParameter("PARAM_CustomerKinId", pARAM_CustomerKinId) :
                new ObjectParameter("PARAM_CustomerKinId", typeof(long));
    
            var pARAM_fkCustomerIdParameter = pARAM_fkCustomerId.HasValue ?
                new ObjectParameter("PARAM_fkCustomerId", pARAM_fkCustomerId) :
                new ObjectParameter("PARAM_fkCustomerId", typeof(long));
    
            var pARAM_KinNameParameter = pARAM_KinName != null ?
                new ObjectParameter("PARAM_KinName", pARAM_KinName) :
                new ObjectParameter("PARAM_KinName", typeof(string));
    
            var pARAM_KinCNICParameter = pARAM_KinCNIC != null ?
                new ObjectParameter("PARAM_KinCNIC", pARAM_KinCNIC) :
                new ObjectParameter("PARAM_KinCNIC", typeof(string));
    
            var pARAM_KinMobileParameter = pARAM_KinMobile != null ?
                new ObjectParameter("PARAM_KinMobile", pARAM_KinMobile) :
                new ObjectParameter("PARAM_KinMobile", typeof(string));
    
            var pARAM_KinRelationParameter = pARAM_KinRelation != null ?
                new ObjectParameter("PARAM_KinRelation", pARAM_KinRelation) :
                new ObjectParameter("PARAM_KinRelation", typeof(string));
    
            var pARAM_ActiveYNParameter = pARAM_ActiveYN != null ?
                new ObjectParameter("PARAM_ActiveYN", pARAM_ActiveYN) :
                new ObjectParameter("PARAM_ActiveYN", typeof(string));
    
            var pARAM_CreatedByParameter = pARAM_CreatedBy != null ?
                new ObjectParameter("PARAM_CreatedBy", pARAM_CreatedBy) :
                new ObjectParameter("PARAM_CreatedBy", typeof(string));
    
            var pARAM_CreatedDateParameter = pARAM_CreatedDate.HasValue ?
                new ObjectParameter("PARAM_CreatedDate", pARAM_CreatedDate) :
                new ObjectParameter("PARAM_CreatedDate", typeof(System.DateTime));
    
            var pARAM_UpdatedByParameter = pARAM_UpdatedBy != null ?
                new ObjectParameter("PARAM_UpdatedBy", pARAM_UpdatedBy) :
                new ObjectParameter("PARAM_UpdatedBy", typeof(string));
    
            var pARAM_UpdatedDateParameter = pARAM_UpdatedDate.HasValue ?
                new ObjectParameter("PARAM_UpdatedDate", pARAM_UpdatedDate) :
                new ObjectParameter("PARAM_UpdatedDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pro_IDU_CustomerKin", pARM_IDU_STSParameter, pARAM_CustomerKinIdParameter, pARAM_fkCustomerIdParameter, pARAM_KinNameParameter, pARAM_KinCNICParameter, pARAM_KinMobileParameter, pARAM_KinRelationParameter, pARAM_ActiveYNParameter, pARAM_CreatedByParameter, pARAM_CreatedDateParameter, pARAM_UpdatedByParameter, pARAM_UpdatedDateParameter, pARM_ERROR_MESSAGE);
        }
    
        public virtual int Pro_IDU_CustomerRegM(string pARM_IDU_STS, Nullable<long> pARAM_CustomerID, string pARAM_fkProjectID, string pARAM_SubProjID, string pARAM_CustomerRegNo, string pARAM_CustomerName, string pARAM_FatherName, string pARAM_CNIC, string pARAM_Mobile, string pARAM_PresentAddress, string pARAM_PermAddress, string pARAM_OfficeNumber, byte[] pARAM_CustIMG, byte[] pARAM_CNICFrontIMG, byte[] pARAM_CNICBackIMG, string pARAM_DealerYN, string pARAM_ActiveYN, string pARAM_CreatedBy, Nullable<System.DateTime> pARAM_CreatedDate, string pARAM_UpdatedBy, Nullable<System.DateTime> pARAM_UpdatedDate, ObjectParameter pARM_ERROR_MESSAGE, ObjectParameter pARAM_New_CustomerID)
        {
            var pARM_IDU_STSParameter = pARM_IDU_STS != null ?
                new ObjectParameter("PARM_IDU_STS", pARM_IDU_STS) :
                new ObjectParameter("PARM_IDU_STS", typeof(string));
    
            var pARAM_CustomerIDParameter = pARAM_CustomerID.HasValue ?
                new ObjectParameter("PARAM_CustomerID", pARAM_CustomerID) :
                new ObjectParameter("PARAM_CustomerID", typeof(long));
    
            var pARAM_fkProjectIDParameter = pARAM_fkProjectID != null ?
                new ObjectParameter("PARAM_fkProjectID", pARAM_fkProjectID) :
                new ObjectParameter("PARAM_fkProjectID", typeof(string));
    
            var pARAM_SubProjIDParameter = pARAM_SubProjID != null ?
                new ObjectParameter("PARAM_SubProjID", pARAM_SubProjID) :
                new ObjectParameter("PARAM_SubProjID", typeof(string));
    
            var pARAM_CustomerRegNoParameter = pARAM_CustomerRegNo != null ?
                new ObjectParameter("PARAM_CustomerRegNo", pARAM_CustomerRegNo) :
                new ObjectParameter("PARAM_CustomerRegNo", typeof(string));
    
            var pARAM_CustomerNameParameter = pARAM_CustomerName != null ?
                new ObjectParameter("PARAM_CustomerName", pARAM_CustomerName) :
                new ObjectParameter("PARAM_CustomerName", typeof(string));
    
            var pARAM_FatherNameParameter = pARAM_FatherName != null ?
                new ObjectParameter("PARAM_FatherName", pARAM_FatherName) :
                new ObjectParameter("PARAM_FatherName", typeof(string));
    
            var pARAM_CNICParameter = pARAM_CNIC != null ?
                new ObjectParameter("PARAM_CNIC", pARAM_CNIC) :
                new ObjectParameter("PARAM_CNIC", typeof(string));
    
            var pARAM_MobileParameter = pARAM_Mobile != null ?
                new ObjectParameter("PARAM_Mobile", pARAM_Mobile) :
                new ObjectParameter("PARAM_Mobile", typeof(string));
    
            var pARAM_PresentAddressParameter = pARAM_PresentAddress != null ?
                new ObjectParameter("PARAM_PresentAddress", pARAM_PresentAddress) :
                new ObjectParameter("PARAM_PresentAddress", typeof(string));
    
            var pARAM_PermAddressParameter = pARAM_PermAddress != null ?
                new ObjectParameter("PARAM_PermAddress", pARAM_PermAddress) :
                new ObjectParameter("PARAM_PermAddress", typeof(string));
    
            var pARAM_OfficeNumberParameter = pARAM_OfficeNumber != null ?
                new ObjectParameter("PARAM_OfficeNumber", pARAM_OfficeNumber) :
                new ObjectParameter("PARAM_OfficeNumber", typeof(string));
    
            var pARAM_CustIMGParameter = pARAM_CustIMG != null ?
                new ObjectParameter("PARAM_CustIMG", pARAM_CustIMG) :
                new ObjectParameter("PARAM_CustIMG", typeof(byte[]));
    
            var pARAM_CNICFrontIMGParameter = pARAM_CNICFrontIMG != null ?
                new ObjectParameter("PARAM_CNICFrontIMG", pARAM_CNICFrontIMG) :
                new ObjectParameter("PARAM_CNICFrontIMG", typeof(byte[]));
    
            var pARAM_CNICBackIMGParameter = pARAM_CNICBackIMG != null ?
                new ObjectParameter("PARAM_CNICBackIMG", pARAM_CNICBackIMG) :
                new ObjectParameter("PARAM_CNICBackIMG", typeof(byte[]));
    
            var pARAM_DealerYNParameter = pARAM_DealerYN != null ?
                new ObjectParameter("PARAM_DealerYN", pARAM_DealerYN) :
                new ObjectParameter("PARAM_DealerYN", typeof(string));
    
            var pARAM_ActiveYNParameter = pARAM_ActiveYN != null ?
                new ObjectParameter("PARAM_ActiveYN", pARAM_ActiveYN) :
                new ObjectParameter("PARAM_ActiveYN", typeof(string));
    
            var pARAM_CreatedByParameter = pARAM_CreatedBy != null ?
                new ObjectParameter("PARAM_CreatedBy", pARAM_CreatedBy) :
                new ObjectParameter("PARAM_CreatedBy", typeof(string));
    
            var pARAM_CreatedDateParameter = pARAM_CreatedDate.HasValue ?
                new ObjectParameter("PARAM_CreatedDate", pARAM_CreatedDate) :
                new ObjectParameter("PARAM_CreatedDate", typeof(System.DateTime));
    
            var pARAM_UpdatedByParameter = pARAM_UpdatedBy != null ?
                new ObjectParameter("PARAM_UpdatedBy", pARAM_UpdatedBy) :
                new ObjectParameter("PARAM_UpdatedBy", typeof(string));
    
            var pARAM_UpdatedDateParameter = pARAM_UpdatedDate.HasValue ?
                new ObjectParameter("PARAM_UpdatedDate", pARAM_UpdatedDate) :
                new ObjectParameter("PARAM_UpdatedDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pro_IDU_CustomerRegM", pARM_IDU_STSParameter, pARAM_CustomerIDParameter, pARAM_fkProjectIDParameter, pARAM_SubProjIDParameter, pARAM_CustomerRegNoParameter, pARAM_CustomerNameParameter, pARAM_FatherNameParameter, pARAM_CNICParameter, pARAM_MobileParameter, pARAM_PresentAddressParameter, pARAM_PermAddressParameter, pARAM_OfficeNumberParameter, pARAM_CustIMGParameter, pARAM_CNICFrontIMGParameter, pARAM_CNICBackIMGParameter, pARAM_DealerYNParameter, pARAM_ActiveYNParameter, pARAM_CreatedByParameter, pARAM_CreatedDateParameter, pARAM_UpdatedByParameter, pARAM_UpdatedDateParameter, pARM_ERROR_MESSAGE, pARAM_New_CustomerID);
        }
    
        public virtual int Pro_IDU_Files(string pARM_IDU_STS, Nullable<int> pARAM_FileID, string pARAM_FileNumber, string pARAM_fkProjectId, string pARAM_Block, string pARAM_PlotCat, string pARAM_Plot_Factor, string pARAM_PlotNo, Nullable<double> pARAM_PlotSize, Nullable<long> pARAM_ConfirmationFee, string pARAM_AutoPlotNo, Nullable<double> pARAM_PlotRate, Nullable<long> pARAM_TotalPloValue, string pARAM_PlotCatDesc, string pARAM_FileStatus, Nullable<long> pARAM_PlotValue, Nullable<int> pARAM_PlotExtChargs, string pARAM_UnitStatus, string pARAM_CreatedBy, Nullable<System.DateTime> pARAM_CreatedDate, string pARAM_UpdatedBy, Nullable<System.DateTime> pARAM_UpdatedDate, ObjectParameter pARM_ERROR_MESSAGE)
        {
            var pARM_IDU_STSParameter = pARM_IDU_STS != null ?
                new ObjectParameter("PARM_IDU_STS", pARM_IDU_STS) :
                new ObjectParameter("PARM_IDU_STS", typeof(string));
    
            var pARAM_FileIDParameter = pARAM_FileID.HasValue ?
                new ObjectParameter("PARAM_FileID", pARAM_FileID) :
                new ObjectParameter("PARAM_FileID", typeof(int));
    
            var pARAM_FileNumberParameter = pARAM_FileNumber != null ?
                new ObjectParameter("PARAM_FileNumber", pARAM_FileNumber) :
                new ObjectParameter("PARAM_FileNumber", typeof(string));
    
            var pARAM_fkProjectIdParameter = pARAM_fkProjectId != null ?
                new ObjectParameter("PARAM_fkProjectId", pARAM_fkProjectId) :
                new ObjectParameter("PARAM_fkProjectId", typeof(string));
    
            var pARAM_BlockParameter = pARAM_Block != null ?
                new ObjectParameter("PARAM_Block", pARAM_Block) :
                new ObjectParameter("PARAM_Block", typeof(string));
    
            var pARAM_PlotCatParameter = pARAM_PlotCat != null ?
                new ObjectParameter("PARAM_PlotCat", pARAM_PlotCat) :
                new ObjectParameter("PARAM_PlotCat", typeof(string));
    
            var pARAM_Plot_FactorParameter = pARAM_Plot_Factor != null ?
                new ObjectParameter("PARAM_Plot_Factor", pARAM_Plot_Factor) :
                new ObjectParameter("PARAM_Plot_Factor", typeof(string));
    
            var pARAM_PlotNoParameter = pARAM_PlotNo != null ?
                new ObjectParameter("PARAM_PlotNo", pARAM_PlotNo) :
                new ObjectParameter("PARAM_PlotNo", typeof(string));
    
            var pARAM_PlotSizeParameter = pARAM_PlotSize.HasValue ?
                new ObjectParameter("PARAM_PlotSize", pARAM_PlotSize) :
                new ObjectParameter("PARAM_PlotSize", typeof(double));
    
            var pARAM_ConfirmationFeeParameter = pARAM_ConfirmationFee.HasValue ?
                new ObjectParameter("PARAM_ConfirmationFee", pARAM_ConfirmationFee) :
                new ObjectParameter("PARAM_ConfirmationFee", typeof(long));
    
            var pARAM_AutoPlotNoParameter = pARAM_AutoPlotNo != null ?
                new ObjectParameter("PARAM_AutoPlotNo", pARAM_AutoPlotNo) :
                new ObjectParameter("PARAM_AutoPlotNo", typeof(string));
    
            var pARAM_PlotRateParameter = pARAM_PlotRate.HasValue ?
                new ObjectParameter("PARAM_PlotRate", pARAM_PlotRate) :
                new ObjectParameter("PARAM_PlotRate", typeof(double));
    
            var pARAM_TotalPloValueParameter = pARAM_TotalPloValue.HasValue ?
                new ObjectParameter("PARAM_TotalPloValue", pARAM_TotalPloValue) :
                new ObjectParameter("PARAM_TotalPloValue", typeof(long));
    
            var pARAM_PlotCatDescParameter = pARAM_PlotCatDesc != null ?
                new ObjectParameter("PARAM_PlotCatDesc", pARAM_PlotCatDesc) :
                new ObjectParameter("PARAM_PlotCatDesc", typeof(string));
    
            var pARAM_FileStatusParameter = pARAM_FileStatus != null ?
                new ObjectParameter("PARAM_FileStatus", pARAM_FileStatus) :
                new ObjectParameter("PARAM_FileStatus", typeof(string));
    
            var pARAM_PlotValueParameter = pARAM_PlotValue.HasValue ?
                new ObjectParameter("PARAM_PlotValue", pARAM_PlotValue) :
                new ObjectParameter("PARAM_PlotValue", typeof(long));
    
            var pARAM_PlotExtChargsParameter = pARAM_PlotExtChargs.HasValue ?
                new ObjectParameter("PARAM_PlotExtChargs", pARAM_PlotExtChargs) :
                new ObjectParameter("PARAM_PlotExtChargs", typeof(int));
    
            var pARAM_UnitStatusParameter = pARAM_UnitStatus != null ?
                new ObjectParameter("PARAM_UnitStatus", pARAM_UnitStatus) :
                new ObjectParameter("PARAM_UnitStatus", typeof(string));
    
            var pARAM_CreatedByParameter = pARAM_CreatedBy != null ?
                new ObjectParameter("PARAM_CreatedBy", pARAM_CreatedBy) :
                new ObjectParameter("PARAM_CreatedBy", typeof(string));
    
            var pARAM_CreatedDateParameter = pARAM_CreatedDate.HasValue ?
                new ObjectParameter("PARAM_CreatedDate", pARAM_CreatedDate) :
                new ObjectParameter("PARAM_CreatedDate", typeof(System.DateTime));
    
            var pARAM_UpdatedByParameter = pARAM_UpdatedBy != null ?
                new ObjectParameter("PARAM_UpdatedBy", pARAM_UpdatedBy) :
                new ObjectParameter("PARAM_UpdatedBy", typeof(string));
    
            var pARAM_UpdatedDateParameter = pARAM_UpdatedDate.HasValue ?
                new ObjectParameter("PARAM_UpdatedDate", pARAM_UpdatedDate) :
                new ObjectParameter("PARAM_UpdatedDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pro_IDU_Files", pARM_IDU_STSParameter, pARAM_FileIDParameter, pARAM_FileNumberParameter, pARAM_fkProjectIdParameter, pARAM_BlockParameter, pARAM_PlotCatParameter, pARAM_Plot_FactorParameter, pARAM_PlotNoParameter, pARAM_PlotSizeParameter, pARAM_ConfirmationFeeParameter, pARAM_AutoPlotNoParameter, pARAM_PlotRateParameter, pARAM_TotalPloValueParameter, pARAM_PlotCatDescParameter, pARAM_FileStatusParameter, pARAM_PlotValueParameter, pARAM_PlotExtChargsParameter, pARAM_UnitStatusParameter, pARAM_CreatedByParameter, pARAM_CreatedDateParameter, pARAM_UpdatedByParameter, pARAM_UpdatedDateParameter, pARM_ERROR_MESSAGE);
        }
    
        public virtual int Pro_IDU_InstDetail(string pARM_IDU_STS, Nullable<long> pARAM_instDID, Nullable<long> pARAM_fkInstMId, Nullable<int> pARAM_srno, Nullable<int> pARAM_Total, Nullable<int> pARAM_Amount, Nullable<int> pARAM_CustomAmount, Nullable<System.DateTime> pARAM_DueDate, string pARAM_InstType, string pARAM_CreatedBy, Nullable<System.DateTime> pARAM_CreatedDate, string pARAM_UpdatedBy, Nullable<System.DateTime> pARAM_UpdatedDate, ObjectParameter pARM_ERROR_MESSAGE, ObjectParameter pARAM_New_instDID)
        {
            var pARM_IDU_STSParameter = pARM_IDU_STS != null ?
                new ObjectParameter("PARM_IDU_STS", pARM_IDU_STS) :
                new ObjectParameter("PARM_IDU_STS", typeof(string));
    
            var pARAM_instDIDParameter = pARAM_instDID.HasValue ?
                new ObjectParameter("PARAM_instDID", pARAM_instDID) :
                new ObjectParameter("PARAM_instDID", typeof(long));
    
            var pARAM_fkInstMIdParameter = pARAM_fkInstMId.HasValue ?
                new ObjectParameter("PARAM_fkInstMId", pARAM_fkInstMId) :
                new ObjectParameter("PARAM_fkInstMId", typeof(long));
    
            var pARAM_srnoParameter = pARAM_srno.HasValue ?
                new ObjectParameter("PARAM_srno", pARAM_srno) :
                new ObjectParameter("PARAM_srno", typeof(int));
    
            var pARAM_TotalParameter = pARAM_Total.HasValue ?
                new ObjectParameter("PARAM_Total", pARAM_Total) :
                new ObjectParameter("PARAM_Total", typeof(int));
    
            var pARAM_AmountParameter = pARAM_Amount.HasValue ?
                new ObjectParameter("PARAM_Amount", pARAM_Amount) :
                new ObjectParameter("PARAM_Amount", typeof(int));
    
            var pARAM_CustomAmountParameter = pARAM_CustomAmount.HasValue ?
                new ObjectParameter("PARAM_CustomAmount", pARAM_CustomAmount) :
                new ObjectParameter("PARAM_CustomAmount", typeof(int));
    
            var pARAM_DueDateParameter = pARAM_DueDate.HasValue ?
                new ObjectParameter("PARAM_DueDate", pARAM_DueDate) :
                new ObjectParameter("PARAM_DueDate", typeof(System.DateTime));
    
            var pARAM_InstTypeParameter = pARAM_InstType != null ?
                new ObjectParameter("PARAM_InstType", pARAM_InstType) :
                new ObjectParameter("PARAM_InstType", typeof(string));
    
            var pARAM_CreatedByParameter = pARAM_CreatedBy != null ?
                new ObjectParameter("PARAM_CreatedBy", pARAM_CreatedBy) :
                new ObjectParameter("PARAM_CreatedBy", typeof(string));
    
            var pARAM_CreatedDateParameter = pARAM_CreatedDate.HasValue ?
                new ObjectParameter("PARAM_CreatedDate", pARAM_CreatedDate) :
                new ObjectParameter("PARAM_CreatedDate", typeof(System.DateTime));
    
            var pARAM_UpdatedByParameter = pARAM_UpdatedBy != null ?
                new ObjectParameter("PARAM_UpdatedBy", pARAM_UpdatedBy) :
                new ObjectParameter("PARAM_UpdatedBy", typeof(string));
    
            var pARAM_UpdatedDateParameter = pARAM_UpdatedDate.HasValue ?
                new ObjectParameter("PARAM_UpdatedDate", pARAM_UpdatedDate) :
                new ObjectParameter("PARAM_UpdatedDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pro_IDU_InstDetail", pARM_IDU_STSParameter, pARAM_instDIDParameter, pARAM_fkInstMIdParameter, pARAM_srnoParameter, pARAM_TotalParameter, pARAM_AmountParameter, pARAM_CustomAmountParameter, pARAM_DueDateParameter, pARAM_InstTypeParameter, pARAM_CreatedByParameter, pARAM_CreatedDateParameter, pARAM_UpdatedByParameter, pARAM_UpdatedDateParameter, pARM_ERROR_MESSAGE, pARAM_New_instDID);
        }
    
        public virtual int Pro_IDU_InstMaster(string pARM_IDU_STS, Nullable<long> pARAM_InstMId, Nullable<int> pARAM_fkFileID, string pARAM_Type, Nullable<System.DateTime> pARAM_DateOfInst, string pARAM_Nature, Nullable<int> pARAM_NoOfInst, Nullable<long> pARAM_InstAmount, Nullable<int> pARAM_CustomPeriod, Nullable<long> pARAM_CustomAmount, string pARAM_CustomTime, string pARAM_CreatedBy, Nullable<System.DateTime> pARAM_CreatedDate, string pARAM_UpdatedBy, Nullable<System.DateTime> pARAM_UpdatedDate, ObjectParameter pARM_ERROR_MESSAGE, ObjectParameter pARAM_New_InstMId)
        {
            var pARM_IDU_STSParameter = pARM_IDU_STS != null ?
                new ObjectParameter("PARM_IDU_STS", pARM_IDU_STS) :
                new ObjectParameter("PARM_IDU_STS", typeof(string));
    
            var pARAM_InstMIdParameter = pARAM_InstMId.HasValue ?
                new ObjectParameter("PARAM_InstMId", pARAM_InstMId) :
                new ObjectParameter("PARAM_InstMId", typeof(long));
    
            var pARAM_fkFileIDParameter = pARAM_fkFileID.HasValue ?
                new ObjectParameter("PARAM_fkFileID", pARAM_fkFileID) :
                new ObjectParameter("PARAM_fkFileID", typeof(int));
    
            var pARAM_TypeParameter = pARAM_Type != null ?
                new ObjectParameter("PARAM_Type", pARAM_Type) :
                new ObjectParameter("PARAM_Type", typeof(string));
    
            var pARAM_DateOfInstParameter = pARAM_DateOfInst.HasValue ?
                new ObjectParameter("PARAM_DateOfInst", pARAM_DateOfInst) :
                new ObjectParameter("PARAM_DateOfInst", typeof(System.DateTime));
    
            var pARAM_NatureParameter = pARAM_Nature != null ?
                new ObjectParameter("PARAM_Nature", pARAM_Nature) :
                new ObjectParameter("PARAM_Nature", typeof(string));
    
            var pARAM_NoOfInstParameter = pARAM_NoOfInst.HasValue ?
                new ObjectParameter("PARAM_NoOfInst", pARAM_NoOfInst) :
                new ObjectParameter("PARAM_NoOfInst", typeof(int));
    
            var pARAM_InstAmountParameter = pARAM_InstAmount.HasValue ?
                new ObjectParameter("PARAM_InstAmount", pARAM_InstAmount) :
                new ObjectParameter("PARAM_InstAmount", typeof(long));
    
            var pARAM_CustomPeriodParameter = pARAM_CustomPeriod.HasValue ?
                new ObjectParameter("PARAM_CustomPeriod", pARAM_CustomPeriod) :
                new ObjectParameter("PARAM_CustomPeriod", typeof(int));
    
            var pARAM_CustomAmountParameter = pARAM_CustomAmount.HasValue ?
                new ObjectParameter("PARAM_CustomAmount", pARAM_CustomAmount) :
                new ObjectParameter("PARAM_CustomAmount", typeof(long));
    
            var pARAM_CustomTimeParameter = pARAM_CustomTime != null ?
                new ObjectParameter("PARAM_CustomTime", pARAM_CustomTime) :
                new ObjectParameter("PARAM_CustomTime", typeof(string));
    
            var pARAM_CreatedByParameter = pARAM_CreatedBy != null ?
                new ObjectParameter("PARAM_CreatedBy", pARAM_CreatedBy) :
                new ObjectParameter("PARAM_CreatedBy", typeof(string));
    
            var pARAM_CreatedDateParameter = pARAM_CreatedDate.HasValue ?
                new ObjectParameter("PARAM_CreatedDate", pARAM_CreatedDate) :
                new ObjectParameter("PARAM_CreatedDate", typeof(System.DateTime));
    
            var pARAM_UpdatedByParameter = pARAM_UpdatedBy != null ?
                new ObjectParameter("PARAM_UpdatedBy", pARAM_UpdatedBy) :
                new ObjectParameter("PARAM_UpdatedBy", typeof(string));
    
            var pARAM_UpdatedDateParameter = pARAM_UpdatedDate.HasValue ?
                new ObjectParameter("PARAM_UpdatedDate", pARAM_UpdatedDate) :
                new ObjectParameter("PARAM_UpdatedDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pro_IDU_InstMaster", pARM_IDU_STSParameter, pARAM_InstMIdParameter, pARAM_fkFileIDParameter, pARAM_TypeParameter, pARAM_DateOfInstParameter, pARAM_NatureParameter, pARAM_NoOfInstParameter, pARAM_InstAmountParameter, pARAM_CustomPeriodParameter, pARAM_CustomAmountParameter, pARAM_CustomTimeParameter, pARAM_CreatedByParameter, pARAM_CreatedDateParameter, pARAM_UpdatedByParameter, pARAM_UpdatedDateParameter, pARM_ERROR_MESSAGE, pARAM_New_InstMId);
        }
    
        public virtual int Pro_IDU_InstReceived(string pARM_IDU_STS, Nullable<long> pARAM_InstRcvID, Nullable<int> pARAM_fkFileID, Nullable<long> pARAM_fkinstDID, Nullable<int> pARAM_srno, Nullable<int> pARAM_Total, Nullable<int> pARAM_InstAmount, Nullable<int> pARAM_CustomAmount, Nullable<int> pARAM_DiscPercent, Nullable<int> pARAM_DiscAmount, string pARAM_instType, string pARAM_paymentMethod, string pARAM_CreatedBy, Nullable<System.DateTime> pARAM_CreatedDate, string pARAM_UpdatedBy, Nullable<System.DateTime> pARAM_UpdatedDate, ObjectParameter pARM_ERROR_MESSAGE, ObjectParameter pARAM_New_instRcvID)
        {
            var pARM_IDU_STSParameter = pARM_IDU_STS != null ?
                new ObjectParameter("PARM_IDU_STS", pARM_IDU_STS) :
                new ObjectParameter("PARM_IDU_STS", typeof(string));
    
            var pARAM_InstRcvIDParameter = pARAM_InstRcvID.HasValue ?
                new ObjectParameter("PARAM_InstRcvID", pARAM_InstRcvID) :
                new ObjectParameter("PARAM_InstRcvID", typeof(long));
    
            var pARAM_fkFileIDParameter = pARAM_fkFileID.HasValue ?
                new ObjectParameter("PARAM_fkFileID", pARAM_fkFileID) :
                new ObjectParameter("PARAM_fkFileID", typeof(int));
    
            var pARAM_fkinstDIDParameter = pARAM_fkinstDID.HasValue ?
                new ObjectParameter("PARAM_fkinstDID", pARAM_fkinstDID) :
                new ObjectParameter("PARAM_fkinstDID", typeof(long));
    
            var pARAM_srnoParameter = pARAM_srno.HasValue ?
                new ObjectParameter("PARAM_srno", pARAM_srno) :
                new ObjectParameter("PARAM_srno", typeof(int));
    
            var pARAM_TotalParameter = pARAM_Total.HasValue ?
                new ObjectParameter("PARAM_Total", pARAM_Total) :
                new ObjectParameter("PARAM_Total", typeof(int));
    
            var pARAM_InstAmountParameter = pARAM_InstAmount.HasValue ?
                new ObjectParameter("PARAM_InstAmount", pARAM_InstAmount) :
                new ObjectParameter("PARAM_InstAmount", typeof(int));
    
            var pARAM_CustomAmountParameter = pARAM_CustomAmount.HasValue ?
                new ObjectParameter("PARAM_CustomAmount", pARAM_CustomAmount) :
                new ObjectParameter("PARAM_CustomAmount", typeof(int));
    
            var pARAM_DiscPercentParameter = pARAM_DiscPercent.HasValue ?
                new ObjectParameter("PARAM_DiscPercent", pARAM_DiscPercent) :
                new ObjectParameter("PARAM_DiscPercent", typeof(int));
    
            var pARAM_DiscAmountParameter = pARAM_DiscAmount.HasValue ?
                new ObjectParameter("PARAM_DiscAmount", pARAM_DiscAmount) :
                new ObjectParameter("PARAM_DiscAmount", typeof(int));
    
            var pARAM_instTypeParameter = pARAM_instType != null ?
                new ObjectParameter("PARAM_instType", pARAM_instType) :
                new ObjectParameter("PARAM_instType", typeof(string));
    
            var pARAM_paymentMethodParameter = pARAM_paymentMethod != null ?
                new ObjectParameter("PARAM_paymentMethod", pARAM_paymentMethod) :
                new ObjectParameter("PARAM_paymentMethod", typeof(string));
    
            var pARAM_CreatedByParameter = pARAM_CreatedBy != null ?
                new ObjectParameter("PARAM_CreatedBy", pARAM_CreatedBy) :
                new ObjectParameter("PARAM_CreatedBy", typeof(string));
    
            var pARAM_CreatedDateParameter = pARAM_CreatedDate.HasValue ?
                new ObjectParameter("PARAM_CreatedDate", pARAM_CreatedDate) :
                new ObjectParameter("PARAM_CreatedDate", typeof(System.DateTime));
    
            var pARAM_UpdatedByParameter = pARAM_UpdatedBy != null ?
                new ObjectParameter("PARAM_UpdatedBy", pARAM_UpdatedBy) :
                new ObjectParameter("PARAM_UpdatedBy", typeof(string));
    
            var pARAM_UpdatedDateParameter = pARAM_UpdatedDate.HasValue ?
                new ObjectParameter("PARAM_UpdatedDate", pARAM_UpdatedDate) :
                new ObjectParameter("PARAM_UpdatedDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pro_IDU_InstReceived", pARM_IDU_STSParameter, pARAM_InstRcvIDParameter, pARAM_fkFileIDParameter, pARAM_fkinstDIDParameter, pARAM_srnoParameter, pARAM_TotalParameter, pARAM_InstAmountParameter, pARAM_CustomAmountParameter, pARAM_DiscPercentParameter, pARAM_DiscAmountParameter, pARAM_instTypeParameter, pARAM_paymentMethodParameter, pARAM_CreatedByParameter, pARAM_CreatedDateParameter, pARAM_UpdatedByParameter, pARAM_UpdatedDateParameter, pARM_ERROR_MESSAGE, pARAM_New_instRcvID);
        }
    
        public virtual int Pro_IDU_Projects(string pARM_IDU_STS, string pARM_ProjectID, string pARM_ParentID, string pARM_ProjectName, string pARM_ProjectAddress, string pARM_AreaType, string pARM_TotalArea, byte[] pARM_MapIMG, string pARM_ProjectType, string pARM_Main_Sub, string pARM_ActiveYN, string pARM_CreatedBy, Nullable<System.DateTime> pARM_CreatedDate, string pARM_UpdatedBy, Nullable<System.DateTime> pARM_UpdatedDate, ObjectParameter pARM_ERROR_MESSAGE)
        {
            var pARM_IDU_STSParameter = pARM_IDU_STS != null ?
                new ObjectParameter("PARM_IDU_STS", pARM_IDU_STS) :
                new ObjectParameter("PARM_IDU_STS", typeof(string));
    
            var pARM_ProjectIDParameter = pARM_ProjectID != null ?
                new ObjectParameter("PARM_ProjectID", pARM_ProjectID) :
                new ObjectParameter("PARM_ProjectID", typeof(string));
    
            var pARM_ParentIDParameter = pARM_ParentID != null ?
                new ObjectParameter("PARM_ParentID", pARM_ParentID) :
                new ObjectParameter("PARM_ParentID", typeof(string));
    
            var pARM_ProjectNameParameter = pARM_ProjectName != null ?
                new ObjectParameter("PARM_ProjectName", pARM_ProjectName) :
                new ObjectParameter("PARM_ProjectName", typeof(string));
    
            var pARM_ProjectAddressParameter = pARM_ProjectAddress != null ?
                new ObjectParameter("PARM_ProjectAddress", pARM_ProjectAddress) :
                new ObjectParameter("PARM_ProjectAddress", typeof(string));
    
            var pARM_AreaTypeParameter = pARM_AreaType != null ?
                new ObjectParameter("PARM_AreaType", pARM_AreaType) :
                new ObjectParameter("PARM_AreaType", typeof(string));
    
            var pARM_TotalAreaParameter = pARM_TotalArea != null ?
                new ObjectParameter("PARM_TotalArea", pARM_TotalArea) :
                new ObjectParameter("PARM_TotalArea", typeof(string));
    
            var pARM_MapIMGParameter = pARM_MapIMG != null ?
                new ObjectParameter("PARM_MapIMG", pARM_MapIMG) :
                new ObjectParameter("PARM_MapIMG", typeof(byte[]));
    
            var pARM_ProjectTypeParameter = pARM_ProjectType != null ?
                new ObjectParameter("PARM_ProjectType", pARM_ProjectType) :
                new ObjectParameter("PARM_ProjectType", typeof(string));
    
            var pARM_Main_SubParameter = pARM_Main_Sub != null ?
                new ObjectParameter("PARM_Main_Sub", pARM_Main_Sub) :
                new ObjectParameter("PARM_Main_Sub", typeof(string));
    
            var pARM_ActiveYNParameter = pARM_ActiveYN != null ?
                new ObjectParameter("PARM_ActiveYN", pARM_ActiveYN) :
                new ObjectParameter("PARM_ActiveYN", typeof(string));
    
            var pARM_CreatedByParameter = pARM_CreatedBy != null ?
                new ObjectParameter("PARM_CreatedBy", pARM_CreatedBy) :
                new ObjectParameter("PARM_CreatedBy", typeof(string));
    
            var pARM_CreatedDateParameter = pARM_CreatedDate.HasValue ?
                new ObjectParameter("PARM_CreatedDate", pARM_CreatedDate) :
                new ObjectParameter("PARM_CreatedDate", typeof(System.DateTime));
    
            var pARM_UpdatedByParameter = pARM_UpdatedBy != null ?
                new ObjectParameter("PARM_UpdatedBy", pARM_UpdatedBy) :
                new ObjectParameter("PARM_UpdatedBy", typeof(string));
    
            var pARM_UpdatedDateParameter = pARM_UpdatedDate.HasValue ?
                new ObjectParameter("PARM_UpdatedDate", pARM_UpdatedDate) :
                new ObjectParameter("PARM_UpdatedDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pro_IDU_Projects", pARM_IDU_STSParameter, pARM_ProjectIDParameter, pARM_ParentIDParameter, pARM_ProjectNameParameter, pARM_ProjectAddressParameter, pARM_AreaTypeParameter, pARM_TotalAreaParameter, pARM_MapIMGParameter, pARM_ProjectTypeParameter, pARM_Main_SubParameter, pARM_ActiveYNParameter, pARM_CreatedByParameter, pARM_CreatedDateParameter, pARM_UpdatedByParameter, pARM_UpdatedDateParameter, pARM_ERROR_MESSAGE);
        }
    
        public virtual int Pro_IDU_UserLogin(string pARM_IDU_STS, string pARM_USER_ID, string pARM_ROLE_ID, string pARM_NAME, string pARM_RMKS, string pARM_USER_NAME, string pARM_PWD, string pARM_CPWD, string pARM_ACTIVEYN, ObjectParameter pARM_ERROR_MESSAGE)
        {
            var pARM_IDU_STSParameter = pARM_IDU_STS != null ?
                new ObjectParameter("PARM_IDU_STS", pARM_IDU_STS) :
                new ObjectParameter("PARM_IDU_STS", typeof(string));
    
            var pARM_USER_IDParameter = pARM_USER_ID != null ?
                new ObjectParameter("PARM_USER_ID", pARM_USER_ID) :
                new ObjectParameter("PARM_USER_ID", typeof(string));
    
            var pARM_ROLE_IDParameter = pARM_ROLE_ID != null ?
                new ObjectParameter("PARM_ROLE_ID", pARM_ROLE_ID) :
                new ObjectParameter("PARM_ROLE_ID", typeof(string));
    
            var pARM_NAMEParameter = pARM_NAME != null ?
                new ObjectParameter("PARM_NAME", pARM_NAME) :
                new ObjectParameter("PARM_NAME", typeof(string));
    
            var pARM_RMKSParameter = pARM_RMKS != null ?
                new ObjectParameter("PARM_RMKS", pARM_RMKS) :
                new ObjectParameter("PARM_RMKS", typeof(string));
    
            var pARM_USER_NAMEParameter = pARM_USER_NAME != null ?
                new ObjectParameter("PARM_USER_NAME", pARM_USER_NAME) :
                new ObjectParameter("PARM_USER_NAME", typeof(string));
    
            var pARM_PWDParameter = pARM_PWD != null ?
                new ObjectParameter("PARM_PWD", pARM_PWD) :
                new ObjectParameter("PARM_PWD", typeof(string));
    
            var pARM_CPWDParameter = pARM_CPWD != null ?
                new ObjectParameter("PARM_CPWD", pARM_CPWD) :
                new ObjectParameter("PARM_CPWD", typeof(string));
    
            var pARM_ACTIVEYNParameter = pARM_ACTIVEYN != null ?
                new ObjectParameter("PARM_ACTIVEYN", pARM_ACTIVEYN) :
                new ObjectParameter("PARM_ACTIVEYN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pro_IDU_UserLogin", pARM_IDU_STSParameter, pARM_USER_IDParameter, pARM_ROLE_IDParameter, pARM_NAMEParameter, pARM_RMKSParameter, pARM_USER_NAMEParameter, pARM_PWDParameter, pARM_CPWDParameter, pARM_ACTIVEYNParameter, pARM_ERROR_MESSAGE);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int Pro_IDU_CustomerFileBook(string pARM_IDU_STS, Nullable<long> pARAM_FileBookID, Nullable<long> pARAM_fkCustomerID, Nullable<int> pARAM_fkFileID, string pARAM_MemberShipNo, string pARAM_AreaType, Nullable<double> pARAM_Area, Nullable<long> pARAM_Price, Nullable<long> pARAM_DownPayment, Nullable<long> pARAM_ConfirmationFee, Nullable<System.DateTime> pARAM_ConfirmationFeeDate, string pARAM_PayMethod, Nullable<long> pARAM_RegistrationFee, string pARAM_BookingStatus, string pARAM_CreatedBy, Nullable<System.DateTime> pARAM_CreatedDate, string pARAM_UpdatedBy, Nullable<System.DateTime> pARAM_UpdatedDate, ObjectParameter pARM_ERROR_MESSAGE, ObjectParameter pARAM_New_FileBookID)
        {
            var pARM_IDU_STSParameter = pARM_IDU_STS != null ?
                new ObjectParameter("PARM_IDU_STS", pARM_IDU_STS) :
                new ObjectParameter("PARM_IDU_STS", typeof(string));
    
            var pARAM_FileBookIDParameter = pARAM_FileBookID.HasValue ?
                new ObjectParameter("PARAM_FileBookID", pARAM_FileBookID) :
                new ObjectParameter("PARAM_FileBookID", typeof(long));
    
            var pARAM_fkCustomerIDParameter = pARAM_fkCustomerID.HasValue ?
                new ObjectParameter("PARAM_fkCustomerID", pARAM_fkCustomerID) :
                new ObjectParameter("PARAM_fkCustomerID", typeof(long));
    
            var pARAM_fkFileIDParameter = pARAM_fkFileID.HasValue ?
                new ObjectParameter("PARAM_fkFileID", pARAM_fkFileID) :
                new ObjectParameter("PARAM_fkFileID", typeof(int));
    
            var pARAM_MemberShipNoParameter = pARAM_MemberShipNo != null ?
                new ObjectParameter("PARAM_MemberShipNo", pARAM_MemberShipNo) :
                new ObjectParameter("PARAM_MemberShipNo", typeof(string));
    
            var pARAM_AreaTypeParameter = pARAM_AreaType != null ?
                new ObjectParameter("PARAM_AreaType", pARAM_AreaType) :
                new ObjectParameter("PARAM_AreaType", typeof(string));
    
            var pARAM_AreaParameter = pARAM_Area.HasValue ?
                new ObjectParameter("PARAM_Area", pARAM_Area) :
                new ObjectParameter("PARAM_Area", typeof(double));
    
            var pARAM_PriceParameter = pARAM_Price.HasValue ?
                new ObjectParameter("PARAM_Price", pARAM_Price) :
                new ObjectParameter("PARAM_Price", typeof(long));
    
            var pARAM_DownPaymentParameter = pARAM_DownPayment.HasValue ?
                new ObjectParameter("PARAM_DownPayment", pARAM_DownPayment) :
                new ObjectParameter("PARAM_DownPayment", typeof(long));
    
            var pARAM_ConfirmationFeeParameter = pARAM_ConfirmationFee.HasValue ?
                new ObjectParameter("PARAM_ConfirmationFee", pARAM_ConfirmationFee) :
                new ObjectParameter("PARAM_ConfirmationFee", typeof(long));
    
            var pARAM_ConfirmationFeeDateParameter = pARAM_ConfirmationFeeDate.HasValue ?
                new ObjectParameter("PARAM_ConfirmationFeeDate", pARAM_ConfirmationFeeDate) :
                new ObjectParameter("PARAM_ConfirmationFeeDate", typeof(System.DateTime));
    
            var pARAM_PayMethodParameter = pARAM_PayMethod != null ?
                new ObjectParameter("PARAM_PayMethod", pARAM_PayMethod) :
                new ObjectParameter("PARAM_PayMethod", typeof(string));
    
            var pARAM_RegistrationFeeParameter = pARAM_RegistrationFee.HasValue ?
                new ObjectParameter("PARAM_RegistrationFee", pARAM_RegistrationFee) :
                new ObjectParameter("PARAM_RegistrationFee", typeof(long));
    
            var pARAM_BookingStatusParameter = pARAM_BookingStatus != null ?
                new ObjectParameter("PARAM_BookingStatus", pARAM_BookingStatus) :
                new ObjectParameter("PARAM_BookingStatus", typeof(string));
    
            var pARAM_CreatedByParameter = pARAM_CreatedBy != null ?
                new ObjectParameter("PARAM_CreatedBy", pARAM_CreatedBy) :
                new ObjectParameter("PARAM_CreatedBy", typeof(string));
    
            var pARAM_CreatedDateParameter = pARAM_CreatedDate.HasValue ?
                new ObjectParameter("PARAM_CreatedDate", pARAM_CreatedDate) :
                new ObjectParameter("PARAM_CreatedDate", typeof(System.DateTime));
    
            var pARAM_UpdatedByParameter = pARAM_UpdatedBy != null ?
                new ObjectParameter("PARAM_UpdatedBy", pARAM_UpdatedBy) :
                new ObjectParameter("PARAM_UpdatedBy", typeof(string));
    
            var pARAM_UpdatedDateParameter = pARAM_UpdatedDate.HasValue ?
                new ObjectParameter("PARAM_UpdatedDate", pARAM_UpdatedDate) :
                new ObjectParameter("PARAM_UpdatedDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pro_IDU_CustomerFileBook", pARM_IDU_STSParameter, pARAM_FileBookIDParameter, pARAM_fkCustomerIDParameter, pARAM_fkFileIDParameter, pARAM_MemberShipNoParameter, pARAM_AreaTypeParameter, pARAM_AreaParameter, pARAM_PriceParameter, pARAM_DownPaymentParameter, pARAM_ConfirmationFeeParameter, pARAM_ConfirmationFeeDateParameter, pARAM_PayMethodParameter, pARAM_RegistrationFeeParameter, pARAM_BookingStatusParameter, pARAM_CreatedByParameter, pARAM_CreatedDateParameter, pARAM_UpdatedByParameter, pARAM_UpdatedDateParameter, pARM_ERROR_MESSAGE, pARAM_New_FileBookID);
        }
    }
}
