//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Files
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Files()
        {
            this.tbl_InstMaster = new HashSet<tbl_InstMaster>();
            this.tbl_InstReceived = new HashSet<tbl_InstReceived>();
            this.tbl_CustomerFileBook = new HashSet<tbl_CustomerFileBook>();
        }
    
        public int FileID { get; set; }
        public string FileNumber { get; set; }
        public string fkProjectId { get; set; }
        public string Block { get; set; }
        public string PlotCat { get; set; }
        public string Plot_Factor { get; set; }
        public string PlotNo { get; set; }
        public Nullable<double> PlotSize { get; set; }
        public Nullable<long> ConfirmationFee { get; set; }
        public string AutoPlotNo { get; set; }
        public Nullable<double> PlotRate { get; set; }
        public Nullable<long> TotalPloValue { get; set; }
        public string PlotCatDesc { get; set; }
        public Nullable<long> FileStatus { get; set; }
        public string PlotValue { get; set; }
        public Nullable<int> PlotExtChargs { get; set; }
        public string UnitStatus { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual tbl_Projects tbl_Projects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_InstMaster> tbl_InstMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_InstReceived> tbl_InstReceived { get; set; }
        public virtual tbl_UserLogin tbl_UserLogin { get; set; }
        public virtual tbl_UserLogin tbl_UserLogin1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_CustomerFileBook> tbl_CustomerFileBook { get; set; }
    }
}
