//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_InstDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_InstDetail()
        {
            this.tbl_InstReceived = new HashSet<tbl_InstReceived>();
        }
    
        public long instDID { get; set; }
        public long fkInstMId { get; set; }
        public Nullable<int> srno { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<int> CustomAmount { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string InstType { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual tbl_UserLogin tbl_UserLogin { get; set; }
        public virtual tbl_InstMaster tbl_InstMaster { get; set; }
        public virtual tbl_UserLogin tbl_UserLogin1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_InstReceived> tbl_InstReceived { get; set; }
    }
}
