//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_InstMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_InstMaster()
        {
            this.tbl_InstDetail = new HashSet<tbl_InstDetail>();
        }
    
        public long InstMId { get; set; }
        public int fkFileID { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> DateOfInst { get; set; }
        public string Nature { get; set; }
        public Nullable<int> NoOfInst { get; set; }
        public Nullable<long> InstAmount { get; set; }
        public Nullable<int> CustomPeriod { get; set; }
        public Nullable<long> CustomAmount { get; set; }
        public string CustomTime { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual tbl_Files tbl_Files { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_InstDetail> tbl_InstDetail { get; set; }
        public virtual tbl_UserLogin tbl_UserLogin { get; set; }
        public virtual tbl_UserLogin tbl_UserLogin1 { get; set; }
    }
}
