//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_userMenu
    {
        public int fkRoleID { get; set; }
        public string fkMenuID { get; set; }
        public string NAME { get; set; }
        public string TYP { get; set; }
        public string ParentCode { get; set; }
        public string AST { get; set; }
        public string PST { get; set; }
        public string VST { get; set; }
        public string INST { get; set; }
        public string UPST { get; set; }
        public string DLST { get; set; }
        public string CHST { get; set; }
        public string ADST { get; set; }
        public string ICN { get; set; }
    
        public virtual tbl_Menu tbl_Menu { get; set; }
        public virtual tbl_UserRole tbl_UserRole { get; set; }
    }
}
