//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_InstReceived
    {
        public long InstRcvID { get; set; }
        public int fkFileID { get; set; }
        public long fkinstDID { get; set; }
        public Nullable<int> srno { get; set; }
        public int Total { get; set; }
        public Nullable<int> InstAmount { get; set; }
        public Nullable<int> CustomAmount { get; set; }
        public Nullable<int> DiscPercent { get; set; }
        public Nullable<int> DiscAmount { get; set; }
        public string instType { get; set; }
        public string paymentMethod { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual tbl_Files tbl_Files { get; set; }
        public virtual tbl_InstDetail tbl_InstDetail { get; set; }
        public virtual tbl_UserLogin tbl_UserLogin { get; set; }
        public virtual tbl_UserLogin tbl_UserLogin1 { get; set; }
    }
}
