//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CustomerRegM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_CustomerRegM()
        {
            this.tbl_CustomerKin = new HashSet<tbl_CustomerKin>();
            this.tbl_CustomerFileBook = new HashSet<tbl_CustomerFileBook>();
        }
    
        public long CustomerID { get; set; }
        public string fkProjectID { get; set; }
        public string SubProjID { get; set; }
        public string CustomerRegNo { get; set; }
        public string CustomerName { get; set; }
        public string FatherName { get; set; }
        public string CNIC { get; set; }
        public string Mobile { get; set; }
        public string PresentAddress { get; set; }
        public string PermAddress { get; set; }
        public string OfficeNumber { get; set; }
        public byte[] CustIMG { get; set; }
        public byte[] CNICFrontIMG { get; set; }
        public byte[] CNICBackIMG { get; set; }
        public string DealerYN { get; set; }
        public string ActiveYN { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_CustomerKin> tbl_CustomerKin { get; set; }
        public virtual tbl_Projects tbl_Projects { get; set; }
        public virtual tbl_UserLogin tbl_UserLogin { get; set; }
        public virtual tbl_UserLogin tbl_UserLogin1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_CustomerFileBook> tbl_CustomerFileBook { get; set; }
    }
}
