//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_UserLogin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_UserLogin()
        {
            this.tbl_CustomerKin = new HashSet<tbl_CustomerKin>();
            this.tbl_CustomerKin1 = new HashSet<tbl_CustomerKin>();
            this.tbl_CustomerRegM = new HashSet<tbl_CustomerRegM>();
            this.tbl_CustomerRegM1 = new HashSet<tbl_CustomerRegM>();
            this.tbl_Files = new HashSet<tbl_Files>();
            this.tbl_Files1 = new HashSet<tbl_Files>();
            this.tbl_InstDetail = new HashSet<tbl_InstDetail>();
            this.tbl_InstDetail1 = new HashSet<tbl_InstDetail>();
            this.tbl_InstMaster = new HashSet<tbl_InstMaster>();
            this.tbl_InstMaster1 = new HashSet<tbl_InstMaster>();
            this.tbl_InstReceived = new HashSet<tbl_InstReceived>();
            this.tbl_InstReceived1 = new HashSet<tbl_InstReceived>();
            this.tbl_Projects = new HashSet<tbl_Projects>();
            this.tbl_Projects1 = new HashSet<tbl_Projects>();
            this.tbl_CustomerFileBook = new HashSet<tbl_CustomerFileBook>();
            this.tbl_CustomerFileBook1 = new HashSet<tbl_CustomerFileBook>();
        }
    
        public string UserID { get; set; }
        public int fkRoleID { get; set; }
        public string NAME { get; set; }
        public string RMKS { get; set; }
        public string UserName { get; set; }
        public string PWD { get; set; }
        public string CPWD { get; set; }
        public string ActiveYN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_CustomerKin> tbl_CustomerKin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_CustomerKin> tbl_CustomerKin1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_CustomerRegM> tbl_CustomerRegM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_CustomerRegM> tbl_CustomerRegM1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Files> tbl_Files { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Files> tbl_Files1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_InstDetail> tbl_InstDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_InstDetail> tbl_InstDetail1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_InstMaster> tbl_InstMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_InstMaster> tbl_InstMaster1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_InstReceived> tbl_InstReceived { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_InstReceived> tbl_InstReceived1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Projects> tbl_Projects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Projects> tbl_Projects1 { get; set; }
        public virtual tbl_UserRole tbl_UserRole { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_CustomerFileBook> tbl_CustomerFileBook { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_CustomerFileBook> tbl_CustomerFileBook1 { get; set; }
    }
}
