//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_user_with_role
    {
        public string UserID { get; set; }
        public int fkRoleID { get; set; }
        public string NAME { get; set; }
        public string LoginName { get; set; }
        public string RMKS { get; set; }
        public string UserName { get; set; }
        public string PWD { get; set; }
        public string CPWD { get; set; }
        public string ActiveYN { get; set; }
    }
}
