//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Installment_Receive
    {
        public long instDID { get; set; }
        public long fkInstMId { get; set; }
        public Nullable<int> srno { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<int> CustomAmount { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string InstType { get; set; }
        public long CustomerID { get; set; }
        public string fkProjectID { get; set; }
        public string CustomerName { get; set; }
        public string CustomerRegNo { get; set; }
        public int fkFileID { get; set; }
        public long FileBookID { get; set; }
        public Nullable<long> InstRcvID { get; set; }
    }
}
